[theme]
base                     = "dark"
primaryColor             = "#7C5CFF"
backgroundColor          = "#050816"
secondaryBackgroundColor = "#0B1220"
textColor                = "#F8FAFC"
font                     = "sans serif"

[server]
headless = true
